/* Paper & Tide — editorial coastal modern. This page uses asymmetry, shell ivory, deep marine, terracotta coral, and quiet motion. */
import { useEffect, useMemo, useState } from "react";
import { ArrowDown, ArrowUpRight, CalendarDays, Check, ChevronLeft, ChevronRight, Copy, Heart, MapPin, Music2, Pause, Play, Send, X } from "lucide-react";

const CONFIG = {
  couple: "Rania & Arga", shortNames: "Rania & Arga", parents: "Putri dari Bapak H. Rahman & Ibu Siti Aminah · Putra dari Bapak D. Surya & Ibu Lestari",
  date: "12 Oktober 2026", eventDate: "2026-10-12T10:00:00+07:00", akad: "10.00 WIB", reception: "12.30–15.00 WIB",
  venue: "Samudra House", address: "Jl. Pantai Selatan No. 18, Pecatu, Bali", maps: "https://maps.google.com/?q=Samudra+House+Bali",
  bank: "BCA", account: "1234567890", recipient: "Rania Putri", wallet: "0812 3456 7890", provider: "GoPay",
  music: "https://cdn.pixabay.com/download/audio/2022/10/25/audio_946b7d1c4a.mp3?filename=romantic-piano-ambient-124097.mp3",
};
const photos = [
  {src:"https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=85", alt:"Pasangan berjalan di lorong dengan cahaya hangat", caption:"The beginning"},
  {src:"https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1000&q=85", alt:"Tangan pasangan dengan cincin pernikahan", caption:"A little promise"},
  {src:"https://images.unsplash.com/photo-1507504031003-b417219a0fde?auto=format&fit=crop&w=1200&q=85", alt:"Pasangan duduk berdua di bawah pohon", caption:"Under the same sky"},
  {src:"https://images.unsplash.com/photo-1523438885200-e635ba2c371e?auto=format&fit=crop&w=1000&q=85", alt:"Detail bunga putih dan kain linen", caption:"Softly, always"},
  {src:"https://images.unsplash.com/photo-1494972308805-463bc619d34e?auto=format&fit=crop&w=1200&q=85", alt:"Mobil klasik melaju menuju garis pantai", caption:"Our way home"},
  {src:"https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&w=1000&q=85", alt:"Pasangan tertawa bersama di luar ruangan", caption:"Still choosing you"},
];
function guestName(){ const raw = new URLSearchParams(window.location.search).get("to")?.trim().replace(/\s+/g," ") || "Tamu undangan"; return raw.slice(0,60); }
function calendarUrl(){ const start="20261012T030000Z", end="20261012T080000Z"; return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(`Pernikahan ${CONFIG.couple}`)}&dates=${start}/${end}&details=${encodeURIComponent("Dengan penuh sukacita, kami mengundang Anda untuk hadir dan berbagi hari istimewa kami.")}&location=${encodeURIComponent(`${CONFIG.venue}, ${CONFIG.address}`)}&ctz=Asia/Jakarta`; }
export default function Home(){
  const [opened,setOpened]=useState(false), [musicOn,setMusicOn]=useState(false), [lightbox,setLightbox]=useState<number|null>(null), [copied,setCopied]=useState(""), [rsvp,setRsvp]=useState({name:"",status:"Hadir",message:""}), [messages,setMessages]=useState<{name:string;status:string;message:string}[]>([]);
  const [now,setNow]=useState(Date.now()); const [submitted,setSubmitted]=useState(false);
  const audio = useMemo(()=>new Audio(CONFIG.music),[]); const target = new Date(CONFIG.eventDate).getTime(); const diff=Math.max(0,target-now); const time={days:Math.floor(diff/86400000),hours:Math.floor(diff/3600000)%24,minutes:Math.floor(diff/60000)%60,seconds:Math.floor(diff/1000)%60};
  useEffect(()=>{const i=setInterval(()=>setNow(Date.now()),1000); return()=>clearInterval(i)},[]);
  useEffect(()=>{audio.loop=true;audio.volume=.24;return()=>audio.pause()},[audio]);
  useEffect(()=>{const els=document.querySelectorAll(".reveal"); if(window.matchMedia("(prefers-reduced-motion: reduce)").matches){els.forEach(e=>e.classList.add("is-visible"));return} const ob=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("is-visible");ob.unobserve(e.target)}}),{threshold:.12}); els.forEach(e=>ob.observe(e)); return()=>ob.disconnect()},[opened]);
  useEffect(()=>{document.body.style.overflow=lightbox!==null?"hidden":""; const key=(e:KeyboardEvent)=>{if(lightbox===null)return;if(e.key==="Escape")setLightbox(null);if(e.key==="ArrowRight")setLightbox((lightbox+1)%photos.length);if(e.key==="ArrowLeft")setLightbox((lightbox+photos.length-1)%photos.length)};window.addEventListener("keydown",key);return()=>{document.body.style.overflow="";window.removeEventListener("keydown",key)}},[lightbox]);
  const open=()=>{setOpened(true); audio.play().then(()=>setMusicOn(true)).catch(()=>setMusicOn(false)); setTimeout(()=>document.getElementById("top")?.scrollIntoView(),20)};
  const toggleMusic=()=>{if(musicOn){audio.pause();setMusicOn(false)}else{audio.play().then(()=>setMusicOn(true)).catch(()=>{})}};
  const copy=(key:string,text:string)=>{if(navigator.clipboard) navigator.clipboard.writeText(text); else {const t=document.createElement("textarea");t.value=text;document.body.appendChild(t);t.select();document.execCommand("copy");t.remove()} setCopied(key);setTimeout(()=>setCopied(""),2000)};
  const submit=(e:React.FormEvent)=>{e.preventDefault(); if(!rsvp.name.trim()||!rsvp.message.trim()){setSubmitted(false);return} setMessages(m=>[...m,{...rsvp,name:rsvp.name.trim(),message:rsvp.message.trim()}]);setSubmitted(true);setRsvp({name:"",status:"Hadir",message:""})};
  return <div className={`site ${opened?"is-open":""}`} id="top">
    <div className="cover" aria-hidden={opened}><div className="cover-image"/><div className="cover-shade"/><div className="cover-content"><div className="emblem">☼</div><p className="eyebrow light">A day by the sea · 12.10.26</p><h1>Rania <i>&</i> Arga</h1><p className="cover-note">Untuk <strong>{guestName()}</strong></p><button className="button button-light" onClick={open}>Buka undangan <ArrowUpRight size={16}/></button></div><div className="cover-foot">Scroll untuk membuka cerita <ArrowDown size={15}/></div></div>
    <header className="topbar"><a className="brand" href="#top"><span className="mini-emblem">☼</span><span>R <i>&</i> A</span></a><nav>{[["cerita","Cerita"],["acara","Acara"],["galeri","Galeri"],["rsvp","RSVP"],["kasih","Tanda kasih"]].map(([id,label])=><a href={`#${id}`} key={id}>{label}</a>)}</nav><span className="top-date">12 · 10 · 26</span></header>
    <button className="music" onClick={toggleMusic} aria-label={musicOn?"Jeda musik":"Putar musik"}>{musicOn?<Pause size={16}/>:<Music2 size={16}/>}<span>{musicOn?"Jeda musik":"Putar musik"}</span></button>
    <main>
      <section className="hero section-pad"><div className="chapter">01 <span>sebuah pertemuan</span></div><div className="hero-grid"><div className="hero-copy reveal"><p className="eyebrow">The quiet kind of forever</p><h2>Yang kami temukan<br/><em>di antara jeda.</em></h2><p className="lede">Ada hari-hari yang tidak direncanakan, namun diam-diam mengubah seluruh arah pulang. Kami menemukan hari itu dalam satu sama lain.</p><a className="text-link" href="#cerita">Baca cerita kami <ArrowDown size={16}/></a></div><div className="hero-photo reveal"><img src={photos[0].src} alt={photos[0].alt}/><span className="photo-label">Pecatu · 2025</span></div></div></section>
      <section id="cerita" className="story section-pad"><div className="chapter">02 <span>catatan kecil</span></div><div className="story-grid"><div className="story-title reveal"><p className="eyebrow">Our story</p><h2>Dari obrolan kecil,<br/><em>menjadi rumah.</em></h2></div><div className="story-body reveal"><p>Pertemuan pertama kami tidak datang dengan kembang api. Hanya dua orang yang duduk terlalu lama di kedai kopi, membicarakan laut, buku, dan kota-kota yang ingin didatangi.</p><p>Sejak itu, kami belajar bahwa rumah bukan selalu tempat. Kadang ia adalah seseorang yang membuat dunia terasa cukup tenang untuk ditinggali.</p><div className="signature">Rania <span>&</span> Arga</div></div><img className="story-image reveal" src={photos[1].src} alt={photos[1].alt}/></div></section>
      <section id="acara" className="event section-pad"><div className="chapter">03 <span>hari yang kami tunggu</span></div><div className="event-head reveal"><p className="eyebrow">Save the date</p><h2>Senin, 12 Oktober<br/><em>dua ribu dua puluh enam.</em></h2><a href={calendarUrl()} target="_blank" rel="noreferrer" className="button button-coral"><CalendarDays size={16}/> Simpan ke kalender</a></div><div className="countdown reveal">{Object.entries({days:"hari",hours:"jam",minutes:"menit",seconds:"detik"}).map(([k,label])=><div className="count" key={k}><strong>{String(time[k as keyof typeof time]).padStart(2,"0")}</strong><span>{label}</span></div>)}</div><div className="event-list"><article className="event-row reveal"><span className="event-time">10.00<br/><small>WIB</small></span><div><p className="eyebrow">Akad nikah</p><h3>Samudra House</h3><p>{CONFIG.address}</p></div><a href={CONFIG.maps} target="_blank" rel="noreferrer" aria-label="Lihat lokasi akad"><MapPin size={18}/></a></article><article className="event-row reveal"><span className="event-time">12.30<br/><small>WIB</small></span><div><p className="eyebrow">Resepsi</p><h3>Samudra House</h3><p>{CONFIG.address}</p></div><a href={CONFIG.maps} target="_blank" rel="noreferrer" aria-label="Lihat lokasi resepsi"><MapPin size={18}/></a></article></div></section>
      <section id="galeri" className="gallery section-pad"><div className="chapter">04 <span>frame yang tersimpan</span></div><div className="gallery-head reveal"><p className="eyebrow">A few frames</p><h2>Little moments,<br/><em>kept close.</em></h2></div><div className="masonry">{photos.map((p,i)=><button className={`gallery-item g${i+1} reveal`} key={p.src} onClick={()=>setLightbox(i)} aria-label={`Lihat foto: ${p.alt}`}><img src={p.src} alt={p.alt}/><span>{String(i+1).padStart(2,"0")} · {p.caption}</span></button>)}</div></section>
      <section id="rsvp" className="rsvp section-pad"><div className="chapter">05 <span>tinggalkan kabar</span></div><div className="rsvp-grid"><div className="reveal"><p className="eyebrow">Will you join us?</p><h2>Hadir atau tidak,<br/><em>kabar darimu berarti.</em></h2><p className="muted">Isi konfirmasi singkat dan titipkan satu kalimat untuk kami baca setelah hari ini.</p></div><form onSubmit={submit} className="form reveal"><label htmlFor="name">Nama lengkap</label><input id="name" value={rsvp.name} onChange={e=>setRsvp({...rsvp,name:e.target.value})} placeholder="Tulis namamu"/><label>Status kehadiran</label><div className="status-options">{["Hadir","Belum bisa memastikan","Tidak dapat hadir"].map(s=><button type="button" className={rsvp.status===s?"selected":""} onClick={()=>setRsvp({...rsvp,status:s})} key={s}>{rsvp.status===s&&<Check size={14}/>} {s}</button>)}</div><label htmlFor="message">Pesan ucapan</label><textarea id="message" rows={4} value={rsvp.message} onChange={e=>setRsvp({...rsvp,message:e.target.value})} placeholder="Tulis doa dan ucapanmu..."/><button className="button button-marine" type="submit"><Send size={16}/> Kirim konfirmasi</button>{submitted&&<p className="success"><Check size={15}/> Terima kasih, konfirmasimu sudah tercatat di perangkat ini.</p>}</form></div><div className="guestbook reveal"><p className="eyebrow">Guestbook</p>{messages.length===0?<p className="empty">Pesan ucapanmu akan muncul di sini setelah dikirim.</p>:messages.map((m,i)=><div className="guest" key={i}><div><strong>{m.name}</strong><span>{m.status}</span></div><p>“{m.message}”</p></div>)}</div></section>
      <section id="kasih" className="gift section-pad"><div className="chapter">06 <span>tanda kasih</span></div><div className="gift-grid"><div className="reveal"><p className="eyebrow">A little kindness</p><h2>Doa dan kehadiranmu<br/><em>sudah lebih dari cukup.</em></h2><p className="muted">Bagi yang ingin mengirim tanda kasih, dapat melalui pilihan berikut.</p></div><div className="gift-card reveal"><div className="qr">{Array.from({length:64}).map((_,i)=><i key={i} style={{opacity:[1,3,5,8,12,17,21,24,29,33,36,41,44,48,52,57,60,62].includes(i)?1:.12}}/>)}</div><p className="eyebrow">{CONFIG.provider}</p><h3>{CONFIG.wallet}</h3><p>{CONFIG.recipient}</p><button onClick={()=>copy("wallet",CONFIG.wallet)} className="copy-button"><Copy size={14}/> {copied==="wallet"?"Tersalin":"Salin nomor"}</button></div><div className="gift-card bank reveal"><div className="bank-mark">{CONFIG.bank}</div><p className="eyebrow">Rekening bank</p><h3>{CONFIG.account}</h3><p>{CONFIG.recipient}</p><button onClick={()=>copy("bank",CONFIG.account)} className="copy-button"><Copy size={14}/> {copied==="bank"?"Tersalin":"Salin nomor"}</button></div></div></section>
    </main><footer><div className="emblem">☼</div><h2>See you by the sea.</h2><p>Dengan hangat, Rania & Arga</p><div className="footer-line">12 · 10 · 26 <span>♡</span> Pecatu, Bali</div></footer>
    {lightbox!==null&&<div className="lightbox" role="dialog" aria-modal="true" aria-label="Galeri foto" onClick={()=>setLightbox(null)}><button className="lb-close" onClick={()=>setLightbox(null)} aria-label="Tutup"><X/></button><button className="lb-prev" onClick={e=>{e.stopPropagation();setLightbox((lightbox+photos.length-1)%photos.length)}} aria-label="Foto sebelumnya"><ChevronLeft/></button><figure onClick={e=>e.stopPropagation()}><img src={photos[lightbox].src} alt={photos[lightbox].alt}/><figcaption>{String(lightbox+1).padStart(2,"0")} · {photos[lightbox].caption}</figcaption></figure><button className="lb-next" onClick={e=>{e.stopPropagation();setLightbox((lightbox+1)%photos.length)}} aria-label="Foto berikutnya"><ChevronRight/></button></div>}
  </div>
}
